# Generated by Django 5.0.1 on 2024-02-15 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_rename_name_inventory_vehicle_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventory',
            old_name='quantity_in_stock',
            new_name='quantity_in_fleet',
        ),
    ]
