# Generated by Django 5.0.1 on 2024-02-15 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_rename_quantity_in_stock_inventory_quantity_in_fleet'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventory',
            old_name='quantity_sold',
            new_name='quantity_in_use',
        ),
    ]
