# Generated by Django 5.0.1 on 2024-02-15 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_rename_quantity_sold_inventory_quantity_in_use'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventory',
            old_name='cost_per_item',
            new_name='cost_per_refuel',
        ),
    ]
