# Generated by Django 5.0.1 on 2024-02-15 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_rename_cost_per_item_inventory_cost_per_refuel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventory',
            old_name='sales',
            new_name='total',
        ),
    ]
