# Generated by Django 5.0.1 on 2024-02-16 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_rename_sales_inventory_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='quantity_in_use',
            field=models.PositiveIntegerField(),
        ),
    ]
