# Generated by Django 5.0.1 on 2024-02-16 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_alter_inventory_quantity_in_use'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='quantity_in_fleet',
            field=models.PositiveIntegerField(),
        ),
    ]
