# Generated by Django 5.0.1 on 2024-02-16 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_alter_inventory_quantity_in_fleet'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventory',
            old_name='stock_date',
            new_name='entry_date',
        ),
    ]
