# Generated by Django 5.0.1 on 2024-02-16 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_rename_stock_date_inventory_entry_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventory',
            old_name='last_sales_date',
            new_name='last_update',
        ),
    ]
