# Generated by Django 5.0.1 on 2024-02-18 11:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_rename_last_sales_date_inventory_last_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='cost_per_refuel',
            field=models.DecimalField(decimal_places=2, max_digits=20, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
    ]
