# Generated by Django 5.0.1 on 2024-02-22 22:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_rename_main_inventory_maintenance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='maintenance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
