# Generated by Django 5.0.1 on 2024-02-22 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_alter_inventory_maintenance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='maintenance',
        ),
    ]
