# Generated by Django 5.0.1 on 2024-02-26 08:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0018_remove_inventory_maintenance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='cost_per_refuel',
            field=models.DecimalField(decimal_places=2, max_digits=20, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
