# Generated by Django 5.0.1 on 2024-02-26 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0020_inventory_main'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventory',
            old_name='main',
            new_name='maintenance',
        ),
    ]
