# Generated by Django 5.0.1 on 2024-02-26 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0022_rename_maintenance_inventory_main'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='main',
        ),
    ]
