# Generated by Django 5.0.1 on 2024-02-26 08:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0023_remove_inventory_main'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='extra',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=20, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
